web/myapp/config/routes.rb
Rails.application.routes.draw do
  resources :questions
  root 'home#index'

  devise_for :accounts
  resources :answers, only: [:create, :destroy]
  resources :answer_replies, only: [:create, :destroy]
  resources :best_answers, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

web/myapp/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :account
  has_many :answers
  has_one :best_answer
  include OwnerCheckable

  scope :with_account, -> {
    eager_load :account
  }
end

web/myapp/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  def index
    @questions = Question.with_account
  end

  # GET /questions/1
  def show
    @answer = Answer.new
    @answer_reply = AnswerReply.new
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    redirect_to questions_url, notice: 'Question was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def question_params
    params.require(:question).permit(:title, :contents).merge(account_id: current_account.id)
  end
end

web/myapp/app/helpers/questions_helper.rb
module QuestionsHelper
end

web/myapp/app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <%= render partial: '/shared/error_messages', locals: { model: question } %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :contents %>
    <%= form.text_area :contents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

web/myapp/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

web/myapp/app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Contents</th>
      <th>Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.contents %></td>
        <td><%= question.account.username %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

web/myapp/app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

web/myapp/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @question.contents %>
</p>

<p>
  <strong>Account:</strong>
  <%= @question.account.username %>
</p>

<% @question.answers.each do |answer| %>
  <p>
    <strong>Answer:</strong>
    <%= answer.contents %>

    <strong>Contributer:</strong>
    <%= answer.account.username %>

    <strong>Created At:</strong>
    <%= answer.created_at %>

    <strong>Updated At:</strong>
    <%= answer.updated_at %>

    <%# 回答削除 %>
    <% if answer.owner?(current_account.id) %>
      <%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>

    <%# ベストアンサー %>
    <% if @question.owner?(current_account.id) %>
      <%
        @best_answer ||= BestAnswer.new
      %>
      <%= render partial: '/shared/error_messages', locals: { model: @best_answer } %>
      <% if answer.best_answer.present? %>
        <%= link_to 'BestDestroy', answer.best_answer, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% else %>
        <%= form_with model: @best_answer, data: {remote: false} do |f| %>
          <%= f.hidden_field :question_id, value: @question.id %>
          <%= f.hidden_field :answer_id, value: answer.id %>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </p>

  <% answer.answer_replies.each do |answer_reply| %>
  <p>
    <strong>Answer Reply:</strong>
    <%= answer_reply.contents %>

    <strong>Contributer:</strong>
    <%= answer_reply.account.username %>

    <strong>Created At:</strong>
    <%= answer_reply.created_at %>

    <strong>Updated At:</strong>
    <%= answer_reply.updated_at %>

    <% if answer_reply.owner?(current_account.id) %>
      <%= link_to 'Destroy', answer_reply, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  <% end %>
  <p>
    <strong>回答返信</strong>
  </p>
  <%
    @answer_reply ||= AnswerReply.new
  %>
  <%= render partial: '/shared/error_messages', locals: { model: @answer_reply } %>
  <%= form_with model: @answer_reply, data: {remote: false} do |f| %>
    <%= f.hidden_field :answer_id, value: answer.id %>
    <%= f.text_area :contents %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

<p>
  <strong>回答</strong>
</p>
<%
  @answer ||= Answer.new
%>
<%= render partial: '/shared/error_messages', locals: { model: @answer } %>
<%= form_with model: @answer, data: {remote: false} do |f| %>
  <%= f.hidden_field :question_id, value: @question.id %>
  <%= f.text_area :contents %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>